// ==UserScript==
// @name            Browse Bot
// @description     Findbar-only AI chat for Zen Browser — page-aware Q&A without URL bar or agentic tools.
// @author          Bibek Bhusal
// @version         3.0.0-findbar-only
// @lastUpdated     2026-02-05
// @ignorecache
// @homepage        https://github.com/Vertex-Mods/Browse-Bot
// ==/UserScript==

// This file was automatically generated. Do not edit this file directly.
// Any changes made here will be overwritten.
// To make changes, please edit the source files in the repository:
// https://github.com/BibekBhusal0/zen-custom-js

import {
  initMarkdownVendors,
  renderMarkdownToElement,
  createProviderFacades,
  resolveProvider,
  buildChatMessages,
  streamChatText,
  completeChatText,
  formatLlmError,
} from "./llm-core.uc.mjs";

function setPref(key, value) {
  try {
    const prefService = Services.prefs;
    if (typeof value === "boolean") {
      prefService.setBoolPref(key, value);
    } else if (typeof value === "number") {
      prefService.setIntPref(key, value);
    } else {
      prefService.setStringPref(key, value);
    }
  } catch {
    //ignore
  }
}

const getPref = (key, defaultValue) => {
  try {
    const prefService = Services.prefs;
    if (prefService.prefHasUserValue(key)) {
      switch (prefService.getPrefType(key)) {
        case prefService.PREF_STRING:
          return prefService.getStringPref(key);
        case prefService.PREF_INT:
          return prefService.getIntPref(key);
        case prefService.PREF_BOOL:
          return prefService.getBoolPref(key);
      }
    }
  } catch {
    return defaultValue;
  }
  return defaultValue;
};

const setPrefIfUnset = (key, value) => {
  if (Services.prefs.getPrefType(key) === 0) {
    setPref(key, value);
  }
};

const resetPref = (key) => {
  if (Services.prefs.getPrefType(key) !== 0) {
    Services.prefs.clearUserPref(key);
  }
};

function addPrefListener(name, callback) {
  const modified_callback = () => {
    callback({ value: getPref(name) });
  };
  Services.prefs.addObserver(name, modified_callback);
  return { name, callback };
}

function removePrefListener(listener) {
  if (listener && listener.name && listener.callback) {
    Services.prefs.removeObserver(listener.name, listener.callback);
  }
}

/** Fixed findbar width (not user-resizable). */
const FINDBAR_WIDTH = 400;

let PREFS$1 = class PREFS {
  static MOD_NAME = "BasePrefs";
  static DEBUG_MODE = "";

  static defaultValues = {};

  static getPref(key, defaultValue = undefined) {
    const defaultVal = defaultValue !== undefined ? defaultValue : this.defaultValues[key];
    return getPref(key, defaultVal);
  }

  static setPref(prefKey, value) {
    setPref(prefKey, value);
  }

  static setInitialPrefs() {
    for (const [key, value] of Object.entries(this.defaultValues)) {
      setPrefIfUnset(key, value);
    }
  }

  static get debugMode() {
    if (!this.DEBUG_MODE) return false;
    return this.getPref(this.DEBUG_MODE);
  }

  static set debugMode(value) {
    if (!this.DEBUG_MODE) return;
    this.setPref(this.DEBUG_MODE, value);
  }

  static debugLog(...args) {
    if (this.debugMode) {
      console.log(`${this.MOD_NAME}:`, ...args);
    }
  }

  static debugError(...args) {
    if (this.debugMode) {
      console.error(`${this.MOD_NAME}:`, ...args);
    }
  }
};

class BrowseBotPREFS extends PREFS$1 {
  static MOD_NAME = "BrowseBot";
  static DEBUG_MODE = "extension.browse-bot.debug-mode";

  static ENABLED = "extension.browse-bot.findbar-ai.enabled";
  static PERSIST = "extension.browse-bot.findbar-ai.persist-chat";
  static STREAM_ENABLED = "extension.browse-bot.findbar-ai.stream-enabled";
  static CONTEXT_MENU_ENABLED = "extension.browse-bot.findbar-ai.context-menu-enabled";
  static CONTEXT_MENU_AUTOSEND = "extension.browse-bot.findbar-ai.context-menu-autosend";
  static CONTEXT_MENU_COMMAND_WITH_SELECTION =
    "extension.browse-bot.findbar-ai.context-menu-command-with-selection";
  static CONTEXT_MENU_COMMAND_NO_SELECTION =
    "extension.browse-bot.findbar-ai.context-menu-command-no-selection";
  static BACKGROUND_STYLE = "extension.browse-bot.findbar-ai.background-style";
  static CUSTOM_SYSTEM_PROMPT = "extension.browse-bot.custom-system-prompt";

  static SHORTCUT_FINDBAR = "extension.browse-bot.findbar-ai.shortcut-findbar";

  static SOLID_BG = "extension.browse-bot.solid-bg";

  static LLM_PROVIDER = "extension.browse-bot.llm-provider";
  static MISTRAL_API_KEY = "extension.browse-bot.mistral-api-key";
  static MISTRAL_MODEL = "extension.browse-bot.mistral-model";
  static GEMINI_API_KEY = "extension.browse-bot.gemini-api-key";
  static GEMINI_MODEL = "extension.browse-bot.gemini-model";
  static OPENAI_API_KEY = "extension.browse-bot.openai-api-key";
  static OPENAI_MODEL = "extension.browse-bot.openai-model";
  static CLAUDE_API_KEY = "extension.browse-bot.claude-api-key";
  static CLAUDE_MODEL = "extension.browse-bot.claude-model";
  static GROK_API_KEY = "extension.browse-bot.grok-api-key";
  static GROK_MODEL = "extension.browse-bot.grok-model";
  static PERPLEXITY_API_KEY = "extension.browse-bot.perplexity-api-key";
  static PERPLEXITY_MODEL = "extension.browse-bot.perplexity-model";
  static CEREBRAS_API_KEY = "extension.browse-bot.cerebras-api-key";
  static CEREBRAS_MODEL = "extension.browse-bot.cerebras-model";
  static OLLAMA_MODEL = "extension.browse-bot.ollama-model";
  static OLLAMA_BASE_URL = "extension.browse-bot.ollama-base-url";

  static LLM_TEMPERATURE = "extension.browse-bot.llm.temperature";
  static LLM_TOP_P = "extension.browse-bot.llm.top-p";
  static LLM_TOP_K = "extension.browse-bot.llm.top-k";
  static LLM_FREQUENCY_PENALTY = "extension.browse-bot.llm.frequency-penalty";
  static LLM_PRESENCE_PENALTY = "extension.browse-bot.llm.presence-penalty";
  static LLM_MAX_OUTPUT_TOKENS = "extension.browse-bot.llm.max-output-tokens";

  // static COPY_BTN_ENABLED = "extension.browse-bot.findbar-ai.copy-btn-enabled";
  // static MARKDOWN_ENABLED = "extension.browse-bot.findbar-ai.markdown-enabled";
  // static SHOW_TOOL_CALL = "extension.browse-bot.findbar-ai.show-tool-call";

  static defaultValues = {
    [BrowseBotPREFS.ENABLED]: true,
    [BrowseBotPREFS.DEBUG_MODE]: false,
    [BrowseBotPREFS.PERSIST]: false,
    [BrowseBotPREFS.STREAM_ENABLED]: true,
    [BrowseBotPREFS.CONTEXT_MENU_ENABLED]: true,
    [BrowseBotPREFS.CONTEXT_MENU_AUTOSEND]: true,
    [BrowseBotPREFS.CONTEXT_MENU_COMMAND_NO_SELECTION]: "Summarize current page",
    [BrowseBotPREFS.CONTEXT_MENU_COMMAND_WITH_SELECTION]:
      "Explain this in context of current page:\n\n{selection}",
    [BrowseBotPREFS.LLM_PROVIDER]: "gemini",
    [BrowseBotPREFS.MISTRAL_API_KEY]: "",
    [BrowseBotPREFS.MISTRAL_MODEL]: "mistral-medium-latest",
    [BrowseBotPREFS.GEMINI_API_KEY]: "",
    [BrowseBotPREFS.GEMINI_MODEL]: "gemini-2.5-flash",
    [BrowseBotPREFS.OPENAI_API_KEY]: "",
    [BrowseBotPREFS.OPENAI_MODEL]: "gpt-5.2",
    [BrowseBotPREFS.CLAUDE_API_KEY]: "",
    [BrowseBotPREFS.CLAUDE_MODEL]: "claude-4-opus",
    [BrowseBotPREFS.GROK_API_KEY]: "",
    [BrowseBotPREFS.GROK_MODEL]: "grok-4",
    [BrowseBotPREFS.PERPLEXITY_API_KEY]: "",
    [BrowseBotPREFS.PERPLEXITY_MODEL]: "sonar",
    [BrowseBotPREFS.CEREBRAS_API_KEY]: "",
    [BrowseBotPREFS.CEREBRAS_MODEL]: "llama3.1-8b",
    [BrowseBotPREFS.OLLAMA_MODEL]: "llama2",
    [BrowseBotPREFS.OLLAMA_BASE_URL]: "http://localhost:11434/api",
    [BrowseBotPREFS.BACKGROUND_STYLE]: "solid",
    [BrowseBotPREFS.SHORTCUT_FINDBAR]: "ctrl+shift+f",
    [BrowseBotPREFS.CUSTOM_SYSTEM_PROMPT]: "",
    [BrowseBotPREFS.LLM_TEMPERATURE]: 0.7,
    [BrowseBotPREFS.LLM_TOP_P]: 1.0,
    [BrowseBotPREFS.LLM_TOP_K]: 40,
    [BrowseBotPREFS.LLM_FREQUENCY_PENALTY]: 0.0,
    [BrowseBotPREFS.LLM_PRESENCE_PENALTY]: 0.0,
    [BrowseBotPREFS.LLM_MAX_OUTPUT_TOKENS]: 2048,
  };

  setInitialPrefs() {
    this.migratePrefs();
    super.setInitialPrefs();
  }

  static migratePrefs() {
    const migrationMap = {
      "extension.browse-bot.enabled": this.ENABLED,
      "extension.browse-bot.persist-chat": this.PERSIST,
      "extension.browse-bot.stream-enabled": this.STREAM_ENABLED,
      "extension.browse-bot.context-menu-enabled": this.CONTEXT_MENU_ENABLED,
      "extension.browse-bot.context-menu-autosend": this.CONTEXT_MENU_AUTOSEND,
    };

    for (const [oldKey, newKey] of Object.entries(migrationMap)) {
      try {
        const oldPref = this.getPref(oldKey);
        if (oldPref != undefined) {
          const value = oldPref;
          this.debugLog(`Migrating pref ${oldKey} to ${newKey} with value: ${value}`);
          this.setPref(newKey, value);
          resetPref(oldPref);
        }
      } catch (e) {
        this.debugError(`Could not migrate pref ${oldKey}:`, e);
      }
    }
  }

  static get enabled() {
    return this.getPref(this.ENABLED);
  }

  static set enabled(value) {
    this.setPref(this.ENABLED, value);
  }

  static get streamEnabled() {
    return this.getPref(this.STREAM_ENABLED);
  }

  static set streamEnabled(value) {
    this.setPref(this.STREAM_ENABLED, value);
  }

  static get contextMenuEnabled() {
    return this.getPref(this.CONTEXT_MENU_ENABLED);
  }

  static set contextMenuEnabled(value) {
    this.setPref(this.CONTEXT_MENU_ENABLED, value);
  }

  static get contextMenuAutoSend() {
    return this.getPref(this.CONTEXT_MENU_AUTOSEND);
  }

  static set contextMenuAutoSend(value) {
    this.setPref(this.CONTEXT_MENU_AUTOSEND, value);
  }

  static get contextMenuCommandWithSelection() {
    return this.getPref(this.CONTEXT_MENU_COMMAND_WITH_SELECTION);
  }

  static set contextMenuCommandWithSelection(value) {
    this.setPref(this.CONTEXT_MENU_COMMAND_WITH_SELECTION, value);
  }

  static get contextMenuCommandNoSelection() {
    return this.getPref(this.CONTEXT_MENU_COMMAND_NO_SELECTION);
  }

  static set contextMenuCommandNoSelection(value) {
    this.setPref(this.CONTEXT_MENU_COMMAND_NO_SELECTION, value);
  }

  static get llmProvider() {
    return this.getPref(this.LLM_PROVIDER);
  }

  static set llmProvider(value) {
    this.setPref(this.LLM_PROVIDER, value);
  }

  static get persistChat() {
    return this.getPref(this.PERSIST);
  }

  static set persistChat(value) {
    this.setPref(this.PERSIST, value);
  }

  static get backgroundStyle() {
    return this.getPref(this.BACKGROUND_STYLE);
  }

  static get pseudoBg() {
    return this.backgroundStyle === "pseudo";
  }

  // static get copyBtnEnabled() {
  //   return this.getPref(this.COPY_BTN_ENABLED);
  // }
  //
  // static set copyBtnEnabled(value) {
  //   this.setPref(this.COPY_BTN_ENABLED, value);
  // }
  //
  // static get markdownEnabled() {
  //   return this.getPref(this.MARKDOWN_ENABLED);
  // }
  //
  // static set markdownEnabled(value) {
  //   this.setPref(this.MARKDOWN_ENABLED, value);
  // }

  // static get showToolCall() {
  //   return this.getPref(this.SHOW_TOOL_CALL);
  // }
  //
  // static set showToolCall(value) {
  //   this.setPref(this.SHOW_TOOL_CALL, value);
  // }

  static get ollamaBaseUrl() {
    return this.getPref(this.OLLAMA_BASE_URL);
  }

  static set ollamaBaseUrl(value) {
    this.setPref(this.OLLAMA_BASE_URL, value);
  }

  static get llmTemperature() {
    return this.getPref(this.LLM_TEMPERATURE);
  }

  static set llmTemperature(value) {
    this.setPref(this.LLM_TEMPERATURE, value);
  }

  static get llmTopP() {
    return this.getPref(this.LLM_TOP_P);
  }

  static set llmTopP(value) {
    this.setPref(this.LLM_TOP_P, value);
  }

  static get llmTopK() {
    return this.getPref(this.LLM_TOP_K);
  }

  static set llmTopK(value) {
    this.setPref(this.LLM_TOP_K, value);
  }

  static get llmFrequencyPenalty() {
    return this.getPref(this.LLM_FREQUENCY_PENALTY);
  }

  static set llmFrequencyPenalty(value) {
    this.setPref(this.LLM_FREQUENCY_PENALTY, value);
  }

  static get llmPresencePenalty() {
    return this.getPref(this.LLM_PRESENCE_PENALTY);
  }

  static set llmPresencePenalty(value) {
    this.setPref(this.LLM_PRESENCE_PENALTY, value);
  }

  static get llmMaxOutputTokens() {
    return this.getPref(this.LLM_MAX_OUTPUT_TOKENS);
  }

  static set llmMaxOutputTokens(value) {
    this.setPref(this.LLM_MAX_OUTPUT_TOKENS, value);
  }

  static get shortcutFindbar() {
    return this.getPref(this.SHORTCUT_FINDBAR);
  }

  static set shortcutFindbar(value) {
    this.setPref(this.SHORTCUT_FINDBAR, value);
  }

  static get customSystemPrompt() {
    return this.getPref(this.CUSTOM_SYSTEM_PROMPT);
  }

  static set customSystemPrompt(value) {
    this.setPref(this.CUSTOM_SYSTEM_PROMPT, value);
  }
}

const PREFS = BrowseBotPREFS;

async function frameScript() {
  const getUrlAndTitle = () => {
    return {
      url: content.location.href,
      title: content.document.title,
    };
  };

  const extractTextContent = (trimWhiteSpace = true) => {
    const clonedBody = content.document.body.cloneNode(true);
    const elementsToRemove = clonedBody.querySelectorAll(
      "script, style, meta, noscript, iframe, svg, canvas, input, textarea, select, img, video, audio, object, embed, applet, form, button, link, head"
    );
    elementsToRemove.forEach((el) => el.remove());

    clonedBody.querySelectorAll("br").forEach((br) => {
      br.replaceWith("\n");
    });

    const blockSelector =
      "p, div, li, h1, h2, h3, h4, h5, h6, tr, article, section, header, footer, aside, main, blockquote, pre";
    clonedBody.querySelectorAll(blockSelector).forEach((el) => {
      el.append("\n");
    });

    const textContent = clonedBody.textContent;

    if (trimWhiteSpace) {
      return textContent.replace(/\s+/g, " ").trim();
    }

    return textContent
      .replace(/[ \t\r\f\v]+/g, " ")
      .replace(/ ?\n ?/g, "\n")
      .replace(/\n+/g, "\n")
      .trim();
  };

  const handlers = {
    GetSelectedText: () => {
      const selection = content.getSelection();
      return {
        selectedText: selection.toString(),
        hasSelection: !selection.isCollapsed,
        ...getUrlAndTitle(),
      };
    },

    GetPageTextContent: ({ trimWhiteSpace }) => {
      return {
        textContent: extractTextContent(trimWhiteSpace),
        ...getUrlAndTitle(),
      };
    },
  };

  addMessageListener("FindbarAI:Command", async function (msg) {
    const cmd = msg.data.command;
    const data = msg.data.data || {};
    try {
      const result = await handlers[cmd](data);
      sendAsyncMessage("FindbarAI:Result", { command: cmd, result });
    } catch (e) {
      sendAsyncMessage("FindbarAI:Result", { command: cmd, result: { error: e.message } });
    }
  });
}

let currentMessageManager = null;

const updateMessageManager = () => {
  if (gBrowser && gBrowser.selectedBrowser) {
    const mm = gBrowser.selectedBrowser.messageManager;
    if (mm !== currentMessageManager) {
      currentMessageManager = mm;
      if (!gBrowser.selectedBrowser._findbarAIInjected) {
        const scriptText = `(${frameScript})();`;
        mm.loadFrameScript(
          "data:application/javascript;charset=utf-8," + encodeURIComponent(scriptText),
          false
        );
        gBrowser.selectedBrowser._findbarAIInjected = true;
      }
    }
  }
};

const messageManagerAPI = {
  send(cmd, data = {}) {
    updateMessageManager();
    if (!currentMessageManager) {
      PREFS.debugError("No message manager available.");
      return Promise.reject(new Error("No message manager available."));
    }

    return new Promise((resolve, reject) => {
      const listener = (msg) => {
        if (msg.data.command === cmd) {
          currentMessageManager.removeMessageListener("FindbarAI:Result", listener);
          if (msg.data.result && msg.data.result.error) {
            reject(new Error(msg.data.result.error));
          } else {
            resolve(msg.data.result);
          }
        }
      };
      currentMessageManager.addMessageListener("FindbarAI:Result", listener);
      currentMessageManager.sendAsyncMessage("FindbarAI:Command", { command: cmd, data });
    });
  },

  getUrlAndTitle() {
    return {
      url: gBrowser.currentURI.spec,
      title: gBrowser.selectedBrowser.contentTitle,
    };
  },

  async getSelectedText() {
    return this.send("GetSelectedText")
      .then((result) => {
        if (!result || !result.hasSelection) {
          return this.getUrlAndTitle();
        }
        return result;
      })
      .catch((error) => {
        PREFS.debugError("Failed to get selected text:", error);
        return this.getUrlAndTitle();
      });
  },

  async getPageTextContent(trimWhiteSpace = true) {
    return this.send("GetPageTextContent", { trimWhiteSpace }).catch((error) => {
      PREFS.debugError("Failed to get page text content:", error);
      return this.getUrlAndTitle();
    });
  },
};

const parseElement = (elementString, type = "html") => {
  if (type === "xul") {
    return window.MozXULElement.parseXULToFragment(elementString).firstChild;
  }

  let element = new DOMParser().parseFromString(elementString, "text/html");
  if (element.body.children.length) element = element.body.firstChild;
  else element = element.head.firstChild;
  return element;
};

const escapeXmlAttribute = (str) => {
  if (typeof str !== "string") return str;
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
};

/**
 * Creates a unique signature for a keyboard shortcut.
 * @param {KeyboardEvent} event - The keyboard event.
 * @returns {string} A unique signature string.
 */
function eventToShortcutSignature(event) {
  const modifiers = [];
  if (event.ctrlKey || event.metaKey) modifiers.push("ctrl");
  if (event.altKey) modifiers.push("alt");
  if (event.shiftKey) modifiers.push("shift");
  modifiers.push(normalizeKeyName(event.key));
  return modifiers.join("+");
}

function normalizeKeyName(key) {
  if (!key) return "";
  const k = key.toLowerCase();
  if (k === " " || k === "space" || k === "spacebar") return "space";
  return k;
}

/**
 * Creates a unique signature for a shortcut string.
 * @param {string} shortcutStr - The shortcut string (e.g., "Ctrl+K").
 * @returns {string} A unique signature string.
 */
function shortcutStringToSignature(shortcutStr) {
  if (!shortcutStr) return "";
  return shortcutStr
    .toLowerCase()
    .replace(/control/g, "ctrl")
    .replace(/option/g, "alt")
    .split("+")
    .map((s) => normalizeKeyName(s.trim()))
    .join("+");
}

let _shortcuts = new Map();

/**
 * Handles keydown events and executes matching shortcuts.
 * @param {KeyboardEvent} event - The keyboard event.
 */
function handleKeyDown(event) {
  // Don't save if input is in focus
  const t = event.target;
  if (t && (t.tagName === "input" || t.tagName === "textarea" || t.isContentEditable)) {
    return;
  }

  const signature = eventToShortcutSignature(event);
  const shortcut = _shortcuts.get(signature);

  if (shortcut) {
    event.preventDefault();
    event.stopPropagation();
    shortcut.callback(event);
  }
}

/**
 * Initializes the registry and starts listening for keyboard events.
 */
function initShortcutRegistry() {
  window.addEventListener("keydown", handleKeyDown, true);
}

/**
 * Registers a new keyboard shortcut.
 * @param {string} shortcutStr - The shortcut string (e.g., "Ctrl+Shift+K").
 * @param {string} id - A unique identifier for this shortcut.
 * @param {Function} callback - The function to execute when the shortcut is triggered.
 * @returns {boolean} True if registration was successful, false otherwise.
 */
function registerShortcut(shortcutStr, id, callback) {
  if (!shortcutStr || !id || typeof callback !== "function") {
    console.error("registerShortcutInRegistry: Invalid arguments", { shortcutStr, id, callback });
    return false;
  }
  unregisterShortcutById(id);

  const signature = shortcutStringToSignature(shortcutStr);
  _shortcuts.set(signature, { id, callback, shortcutStr });
  return true;
}

/**
 * Unregisters a shortcut by its ID.
 * @param {string} id - The ID of the shortcut to unregister.
 * @returns {boolean} True if unregistration was successful, false otherwise.
 */
function unregisterShortcutById(id) {
  for (const [signature, shortcut] of _shortcuts.entries()) {
    if (shortcut.id === id) {
      _shortcuts.delete(signature);
      return true;
    }
  }
  return false;
}

const SettingsModal = {
  _modalElement: null,
  _currentPrefValues: {},
  _currentShortcutTarget: null,
  _boundHandleShortcutKeyDown: null,

  _getSafeIdForProvider(providerName) {
    return providerName.replace(/\./g, "-");
  },

  _initShortcutHandler() {
    this._boundHandleShortcutKeyDown = this._handleShortcutKeyDown.bind(this);
  },

  _handleShortcutKeyDown(event) {
    if (!this._currentShortcutTarget) return;

    event.preventDefault();
    event.stopPropagation();

    const targetInput = this._currentShortcutTarget;
    const prefKey = targetInput.dataset.pref;

    if (event.key === "Escape") {
      targetInput.value = PREFS.getPref(prefKey);
      targetInput.classList.remove("recording");
      targetInput.placeholder = "Click to set";
      this._currentShortcutTarget = null;
      window.removeEventListener("keydown", this._boundHandleShortcutKeyDown, true);
      return;
    }

    if (event.key === "Backspace" || event.key === "Delete") {
      targetInput.value = "";
      this._currentPrefValues[prefKey] = "";
      targetInput.classList.remove("recording");
      targetInput.placeholder = "Click to set";
      this._currentShortcutTarget = null;
      window.removeEventListener("keydown", this._boundHandleShortcutKeyDown, true);
      return;
    }

    if (["Control", "Alt", "Shift", "Meta"].includes(event.key)) {
      return;
    }

    const shortcutString = eventToShortcutSignature(event);
    targetInput.value = shortcutString;
    this._currentPrefValues[prefKey] = shortcutString;
    PREFS.debugLog(`Shortcut for ${prefKey} set to: ${shortcutString}`);

    targetInput.classList.remove("recording");
    targetInput.placeholder = "Click to set";
    this._currentShortcutTarget = null;
    window.removeEventListener("keydown", this._boundHandleShortcutKeyDown, true);
  },

  _generateShortcutInputHtml(prefConstant, label) {
    const currentValue = PREFS.getPref(prefConstant);
    const prefId = `pref-${prefConstant.toLowerCase().replace(/_/g, "-")}`;
    return `
      <div class="setting-item">
        <label for="${prefId}">${label}</label>
        <input type="text" id="${prefId}" data-pref="${prefConstant}" value="${escapeXmlAttribute(
          currentValue
        )}" readonly placeholder="Click to set" class="shortcut-input" />
      </div>
    `;
  },

  createModalElement() {
    this._initShortcutHandler();
    const settingsHtml = this._generateSettingsHtml();
    const container = parseElement(settingsHtml);
    this._modalElement = container;

    const providerOptionsXUL = Object.entries(browseBotFindbarLLM.AVAILABLE_PROVIDERS)
      .map(
        ([name, provider]) =>
          `<menuitem
            value="${name}"
            label="${escapeXmlAttribute(provider.label)}"
            ${name === PREFS.llmProvider ? 'selected="true"' : ""}
            ${provider.faviconUrl ? `image="${escapeXmlAttribute(provider.faviconUrl)}"` : ""}
          />`
      )
      .join("");

    const menulistXul = `
      <menulist id="pref-llm-provider" data-pref="${PREFS.LLM_PROVIDER}" value="${PREFS.llmProvider}">
        <menupopup>
          ${providerOptionsXUL}
        </menupopup>
      </menulist>`;

    const providerSelectorXulElement = parseElement(menulistXul, "xul");
    const placeholder = this._modalElement.querySelector("#llm-provider-selector-placeholder");
    if (placeholder) {
      placeholder.replaceWith(providerSelectorXulElement);
    }

    for (const [name, provider] of Object.entries(browseBotFindbarLLM.AVAILABLE_PROVIDERS)) {
      const modelPrefKey = provider.modelPref;
      const currentModel = provider.model;

      const modelOptionsXUL = provider.AVAILABLE_MODELS.map(
        (model) =>
          `<menuitem
              value="${model}"
              label="${escapeXmlAttribute(provider.AVAILABLE_MODELS_LABELS[model] || model)}"
              ${model === currentModel ? 'selected="true"' : ""}
            />`
      ).join("");

      const modelMenulistXul = `
          <menulist id="pref-${this._getSafeIdForProvider(name)}-model" data-pref="${modelPrefKey}" value="${currentModel}">
            <menupopup>
              ${modelOptionsXUL}
            </menupopup>
          </menulist>`;

      const modelPlaceholder = this._modalElement.querySelector(
        `#llm-model-selector-placeholder-${this._getSafeIdForProvider(name)}`
      );
      if (modelPlaceholder) {
        const modelSelectorXulElement = parseElement(modelMenulistXul, "xul");
        modelPlaceholder.replaceWith(modelSelectorXulElement);
      }
    }

    this._attachEventListeners();
    return container;
  },

  _attachEventListeners() {
    if (!this._modalElement) return;

    // Close button
    this._modalElement.querySelector("#close-settings").addEventListener("click", () => {
      this.hide();
    });

    // Save button
    this._modalElement.querySelector("#save-settings").addEventListener("click", () => {
      this.saveSettings();
      this.hide();
      if (browseBotFindbar.enabled) browseBotFindbar.show();
      else browseBotFindbar.destroy();
    });

    this._modalElement.addEventListener("click", (e) => {
      if (e.target === this._modalElement) {
        this.hide();
      }
    });

    this._modalElement.querySelectorAll(".accordion-header").forEach((header) => {
      header.addEventListener("click", () => {
        const section = header.closest(".settings-accordion");
        const isExpanded = section.dataset.expanded === "true";
        section.dataset.expanded = isExpanded ? "false" : "true";
      });
    });

    // Initialize and listen to changes on controls (store in _currentPrefValues)
    this._modalElement.querySelectorAll("[data-pref]").forEach((control) => {
      const prefKey = control.dataset.pref;

      // Initialize control value from PREFS
      if (control.type === "checkbox") {
        control.checked = PREFS.getPref(prefKey);
      } else if (control.tagName.toLowerCase() === "menulist") {
        control.value = PREFS.getPref(prefKey);
      } else {
        control.value = PREFS.getPref(prefKey);
      }

      this._currentPrefValues[prefKey] = PREFS.getPref(prefKey);

      // Store changes in _currentPrefValues
      if (control.tagName.toLowerCase() === "menulist") {
        control.addEventListener("command", (e) => {
          this._currentPrefValues[prefKey] = e.target.value;
          PREFS.debugLog(
            `Settings form value for ${prefKey} changed to: ${this._currentPrefValues[prefKey]}`
          );
          if (prefKey === PREFS.LLM_PROVIDER) {
            this._updateProviderSpecificSettings(
              this._modalElement,
              this._currentPrefValues[prefKey]
            );
          }
        });
      } else {
        control.addEventListener("change", (e) => {
          if (control.type === "checkbox") {
            this._currentPrefValues[prefKey] = e.target.checked;
          } else if (control.type === "number") {
            try {
              this._currentPrefValues[prefKey] = Number(e.target.value);
            } catch {
              this._currentPrefValues[prefKey] = 0;
            }
          } else {
            this._currentPrefValues[prefKey] = e.target.value;
          }
          PREFS.debugLog(
            `Settings form value for ${prefKey} changed to: ${this._currentPrefValues[prefKey]}`
          );
        });
      }
    });

    // Attach event listeners for API key links
    this._modalElement.querySelectorAll(".get-api-key-link").forEach((link) => {
      link.addEventListener("click", (e) => {
        e.preventDefault();
        const url = e.target.dataset.url;
        if (url) {
          openTrustedLinkIn(url, "tab");
          this.hide();
        }
      });
    });

    // Attach event listeners for shortcut inputs
    this._modalElement.querySelectorAll(".shortcut-input").forEach((input) => {
      input.addEventListener("focus", (e) => {
        this._currentShortcutTarget = e.target;
        e.target.classList.add("recording");
        e.target.placeholder = "Press keys...";
        window.addEventListener("keydown", this._boundHandleShortcutKeyDown, true);
      });

      input.addEventListener("blur", () => {
        if (this._currentShortcutTarget) {
          this._currentShortcutTarget.classList.remove("recording");
          this._currentShortcutTarget.placeholder = "Click to set";
          this._currentShortcutTarget = null;
          window.removeEventListener("keydown", this._boundHandleShortcutKeyDown, true);
        }
      });

      input.addEventListener("keydown", (e) => {
        e.preventDefault();
        e.stopPropagation();
      });
    });

    // Initial update for provider-specific settings display
    this._updateProviderSpecificSettings(this._modalElement, PREFS.llmProvider);

    // Reset Button Listeners
    this._modalElement.querySelectorAll(".reset-section-btn").forEach((btn) => {
      btn.addEventListener("click", (e) => {
        e.stopPropagation(); // Prevent accordion toggle
        const prefsToReset = btn.dataset.resetPrefs.split(",");
        prefsToReset.forEach((prefKey) => {
          if (!prefKey) return; // skip empty
          const defVal = PREFS.defaultValues[prefKey];

          // Update internal state
          this._currentPrefValues[prefKey] = defVal;

          // Update UI
          const control = this._modalElement.querySelector(`[data-pref="${prefKey}"]`);
          if (control) {
            if (control.type === "checkbox") {
              control.checked = defVal;
            } else if (control.tagName.toLowerCase() === "menulist") {
              control.value = defVal;
            } else {
              control.value = defVal;
            }

            // Special logic for provider reset
            if (prefKey === PREFS.LLM_PROVIDER) {
              this._updateProviderSpecificSettings(this._modalElement, defVal);
            }
          }
        });
      });
    });
  },

  saveSettings() {
    for (const prefKey in this._currentPrefValues) {
      if (Object.prototype.hasOwnProperty.call(this._currentPrefValues, prefKey)) {
        if (prefKey.endsWith("api-key")) {
          if (this._currentPrefValues[prefKey]) {
            const maskedKey = "*".repeat(this._currentPrefValues[prefKey].length);
            PREFS.debugLog(`Saving pref ${prefKey} to: ${maskedKey}`);
          }
        } else {
          PREFS.debugLog(`Saving pref ${prefKey} to: ${this._currentPrefValues[prefKey]}`);
        }
        try {
          PREFS.setPref(prefKey, this._currentPrefValues[prefKey]);
        } catch (e) {
          PREFS.debugError(`Error Saving pref for ${prefKey} ${e}`);
        }
      }
    }
    // Special case: If API key is empty after saving, ensure findbar is collapsed
    if (!browseBotFindbarLLM.currentProvider.apiKey) {
      browseBotFindbar.expanded = false;
    }
  },

  show() {
    this.createModalElement();
    this._modalElement.querySelectorAll("[data-pref]").forEach((control) => {
      const prefKey = control.dataset.pref;
      if (control.type === "checkbox") {
        control.checked = PREFS.getPref(prefKey);
      } else {
        // For XUL menulist, ensure its value is set correctly on show
        if (control.tagName.toLowerCase() === "menulist") {
          control.value = PREFS.getPref(prefKey);
        } else {
          control.value = PREFS.getPref(prefKey);
        }
      }
      this._currentPrefValues[prefKey] = PREFS.getPref(prefKey);
    });
    this._updateProviderSpecificSettings(this._modalElement, PREFS.llmProvider);

    document.documentElement.appendChild(this._modalElement);
  },

  hide() {
    if (this._modalElement && this._modalElement.parentNode) {
      this._modalElement.remove();
    }
  },

  // Helper to show/hide provider-specific settings sections and update model dropdowns
  _updateProviderSpecificSettings(container, selectedProviderName) {
    container.querySelectorAll(".provider-settings-group").forEach((group) => {
      group.style.display = "none";
    });

    // Use the safe ID for the selector
    const activeGroup = container.querySelector(
      `#${this._getSafeIdForProvider(selectedProviderName)}-settings-group`
    );
    if (activeGroup) {
      activeGroup.style.display = "block";

      // Dynamically update the model dropdown for the active provider
      const modelPrefKey = PREFS[`${selectedProviderName.toUpperCase()}_MODEL`];
      if (modelPrefKey) {
        // Use the safe ID for the model selector as well
        const modelSelect = activeGroup.querySelector(
          `#pref-${this._getSafeIdForProvider(selectedProviderName)}-model`
        );
        if (modelSelect) {
          modelSelect.value = this._currentPrefValues[modelPrefKey] || PREFS.getPref(modelPrefKey);
        }
      }
      // Update the "Get API Key" link's state for the active provider
      const provider = browseBotFindbarLLM.AVAILABLE_PROVIDERS[selectedProviderName];
      const getApiKeyLink = activeGroup.querySelector(".get-api-key-link");
      if (getApiKeyLink) {
        if (provider.apiKeyUrl) {
          getApiKeyLink.style.display = "inline-block";
          getApiKeyLink.dataset.url = provider.apiKeyUrl;
        } else {
          getApiKeyLink.style.display = "none";
          delete getApiKeyLink.dataset.url;
        }
      }
    }
  },

  _generateCheckboxSettingHtml(label, prefConstant) {
    const prefId = `pref-${prefConstant.toLowerCase().replace(/_/g, "-")}`;
    return `
      <div class="setting-item">
        <label for="${prefId}">${label}</label>
        <input type="checkbox" id="${prefId}" data-pref="${prefConstant}" />
      </div>
    `;
  },

  _generateNumberSettingHtml(label, prefConstant, min, max, step, tooltip) {
    const prefId = `pref-${prefConstant.toLowerCase().replace(/_/g, "-")}`;
    const infoIconHtml = tooltip
      ? `<span class="info-icon-wrapper" data-tooltip="${escapeXmlAttribute(tooltip)}"><img class="info-icon" src="chrome://global/skin/icons/info.svg" /></span>`
      : "";

    return `
      <div class="setting-item">
        <label for="${prefId}" style="display: flex; align-items: center; gap: 6px;">
          ${label}
          ${infoIconHtml}
        </label>
        <input type="number" id="${prefId}" data-pref="${prefConstant}" min="${min}" max="${max}" step="${step}" />
      </div>
    `;
  },

  _createCheckboxSectionHtml(
    title,
    settingsArray,
    expanded = true,
    contentBefore = "",
    contentAfter = "",
    resetPrefs = []
  ) {
    const settingsHtml = settingsArray
      .map((s) => {
        if (s.type === "number") {
          return this._generateNumberSettingHtml(s.label, s.pref, s.min, s.max, s.step, s.tooltip);
        }
        return this._generateCheckboxSettingHtml(s.label, s.pref);
      })
      .join("");

    // If no explicit resetPrefs passed, try to infer from settingsArray
    const prefsToReset = (
      resetPrefs.length > 0 ? resetPrefs : settingsArray.map((s) => s.pref)
    ).join(",");

    return `
    <section class="settings-section settings-accordion" data-expanded="${expanded}" >
      <h4 class="accordion-header">
        ${title}
        <div class="reset-section-btn" data-reset-prefs="${prefsToReset}" title="Reset Section" role="button">
            <img src="chrome://global/skin/icons/reload.svg" />
        </div>
      </h4>
      <div class="accordion-content">
        ${contentBefore}
        ${settingsHtml}
        ${contentAfter}
      </div>
    </section>
  `;
  },

  _generateSettingsHtml() {
    // Section 1: Findbar
    const findbarSettings = [
      { label: "Enable AI Findbar", pref: PREFS.ENABLED },
      { label: "Persist Chat (don't persist when browser closes)", pref: PREFS.PERSIST },
    ];

    const backgroundStyleOptions = {
      solid: "Solid",
      acrylic: "Acrylic",
      pseudo: "Pseudo",
    };
    const backgroundStyleOptionsHTML = Object.entries(backgroundStyleOptions)
      .map(([value, label]) => `<option value="${value}">${escapeXmlAttribute(label)}</option>`)
      .join("");
    const backgroundStyleSelectorHtml = `
      <div class="setting-item">
        <label for="pref-background-style">Background Style</label>
        <select id="pref-background-style" data-pref="${PREFS.BACKGROUND_STYLE}">
          ${backgroundStyleOptionsHTML}
        </select>
      </div>
    `;

    const findbarResetPrefs = [
      ...findbarSettings.map((s) => s.pref),
      PREFS.BACKGROUND_STYLE,
    ];
    const findbarSectionHtml = this._createCheckboxSectionHtml(
      "Findbar AI",
      findbarSettings,
      true,
      "",
      backgroundStyleSelectorHtml,
      findbarResetPrefs
    );

    // Section 2: Keyboard Shortcuts
    const shortcutFindbarHtml = this._generateShortcutInputHtml(
      PREFS.SHORTCUT_FINDBAR,
      "Open Findbar AI"
    );
    const shortcutsSectionHtml = `
      <section class="settings-section settings-accordion" data-expanded="true">
        <h4 class="accordion-header">
          Keyboard Shortcuts
          <div class="reset-section-btn" data-reset-prefs="${PREFS.SHORTCUT_FINDBAR}" title="Reset Section" role="button">
            <img src="chrome://global/skin/icons/reload.svg" />
          </div>
        </h4>
        <div class="accordion-content">
          ${shortcutFindbarHtml}
        </div>
      </section>
    `;

    // Section 3: AI Behavior
    const aiBehaviorSettings = [{ label: "Stream Response", pref: PREFS.STREAM_ENABLED }];
    const customSystemPromptHtml = `
   <div class="setting-item">
     <label for="pref-custom-system-prompt">Custom System Prompt</label>
     <textarea id="pref-custom-system-prompt" data-pref="${PREFS.CUSTOM_SYSTEM_PROMPT}" rows="3" placeholder="Pretend like ...."></textarea>
   </div>
 `;

    const aiBehaviorResetPrefs = [
      ...aiBehaviorSettings.map((s) => s.pref),
      PREFS.CUSTOM_SYSTEM_PROMPT,
    ];
    const aiBehaviorSectionHtml = this._createCheckboxSectionHtml(
      "AI Behavior",
      aiBehaviorSettings,
      true,
      "",
      customSystemPromptHtml,
      aiBehaviorResetPrefs
    );

    // Section 5: Context Menu
    const contextMenuSettings = [
      { label: "Enable Context Menu (right click menu)", pref: PREFS.CONTEXT_MENU_ENABLED },
      {
        label: "Auto Send from Context Menu",
        pref: PREFS.CONTEXT_MENU_AUTOSEND,
      },
    ];
    const contextMenuCommandsHtml = `
      <div class="setting-item">
        <label for="pref-context-menu-command-no-selection">Command when no text is selected</label>
        <textarea id="pref-context-menu-command-no-selection" data-pref="${PREFS.CONTEXT_MENU_COMMAND_NO_SELECTION}" rows="3"></textarea>
      </div>
      <div class="setting-item">
        <label for="pref-context-menu-command-with-selection">Command when text is selected. Use {selection} for the selected text.</label>
        <textarea id="pref-context-menu-command-with-selection" data-pref="${PREFS.CONTEXT_MENU_COMMAND_WITH_SELECTION}" rows="3"></textarea>
      </div>
    `;
    const contextMenuResetPrefs = [
      ...contextMenuSettings.map((s) => s.pref),
      PREFS.CONTEXT_MENU_COMMAND_NO_SELECTION,
      PREFS.CONTEXT_MENU_COMMAND_WITH_SELECTION,
    ];
    const contextMenuSectionHtml = this._createCheckboxSectionHtml(
      "Context Menu",
      contextMenuSettings,
      false,
      "",
      contextMenuCommandsHtml,
      contextMenuResetPrefs
    );

    // Section 6: LLM Providers
    let llmProviderSettingsHtml = "";
    for (const [name, provider] of Object.entries(browseBotFindbarLLM.AVAILABLE_PROVIDERS)) {
      const modelPrefKey = provider.modelPref;

      let apiInputHtml;
      if (name === "ollama") {
        const baseUrlPrefKey = PREFS.OLLAMA_BASE_URL;
        apiInputHtml = `
        <div class="setting-item">
          <label for="pref-ollama-base-url">Base URL</label>
          <input type="text" id="pref-ollama-base-url" data-pref="${baseUrlPrefKey}" placeholder="http://localhost:11434/api" />
        </div>
      `;
      } else {
        const apiPrefKey = PREFS[`${name.toUpperCase()}_API_KEY`];
        apiInputHtml = apiPrefKey
          ? `
        <div class="setting-item">
          <label for="pref-${this._getSafeIdForProvider(name)}-api-key">API Key</label>
          <input type="password" id="pref-${this._getSafeIdForProvider(name)}-api-key" data-pref="${apiPrefKey}" placeholder="Enter ${provider.label} API Key" />
        </div>
      `
          : "";
      }

      // Placeholder for the XUL menulist, which will be inserted dynamically in createModalElement
      const modelSelectPlaceholderHtml = modelPrefKey
        ? `
        <div class="setting-item">
          <label for="pref-${this._getSafeIdForProvider(name)}-model">Model</label>
          <div id="llm-model-selector-placeholder-${this._getSafeIdForProvider(name)}"></div>
        </div>
      `
        : "";

      llmProviderSettingsHtml += `
        <div id="${this._getSafeIdForProvider(name)}-settings-group" class="provider-settings-group">
          <div class="provider-header-group">
            <h5>${provider.label}</h5>
            <button class="get-api-key-link" data-url="${provider.apiKeyUrl || ""}" style="display: ${provider.apiKeyUrl ? "inline-block" : "none"};">Get API Key</button>
          </div>
          ${apiInputHtml}
          ${modelSelectPlaceholderHtml}
        </div>
      `;
    }

    const llmProvidersResetPrefs = [
      PREFS.LLM_PROVIDER,
      PREFS.OLLAMA_BASE_URL,
      ...Object.values(browseBotFindbarLLM.AVAILABLE_PROVIDERS)
        .flatMap((p) => [p.modelPref, PREFS[`${p.name.toUpperCase()}_API_KEY`]])
        .filter(Boolean),
    ];

    const llmProvidersSectionHtml = `
      <section class="settings-section settings-accordion" data-expanded="false">
        <h4 class="accordion-header">
            LLM Providers
            <div class="reset-section-btn" data-reset-prefs="${llmProvidersResetPrefs.join(",")}" title="Reset Section" role="button">
                <img src="chrome://global/skin/icons/reload.svg" />
            </div>
        </h4>
        <div class="setting-item accordion-content" class="">
          <label for="pref-llm-provider">Select Provider</label>
          <div id="llm-provider-selector-placeholder"></div>
        </div>
        ${llmProviderSettingsHtml}
      </section>`;

    // Section 7: Advanced LLM
    const advancedLLMSettings = [
      {
        label: "Temperature",
        pref: PREFS.LLM_TEMPERATURE,
        type: "number",
        step: 0.1,
        min: 0,
        max: 2,
        tooltip: "Controls randomness. Lower values are more deterministic.",
      },
      {
        label: "Top P  -----", // :HACK: adding space so that tooltip stay under container
        pref: PREFS.LLM_TOP_P,
        type: "number",
        step: 0.1,
        min: 0,
        max: 1,
        tooltip: "Nucleus sampling. Limits token selection to top cumulative probability.",
      },
      {
        label: "Top K  ----- ", // :HACK: adding space so that tooltip stay under container
        pref: PREFS.LLM_TOP_K,
        type: "number",
        step: 1,
        min: 0,
        max: 200,
        tooltip: "Limits sampling to the top K tokens. Removes low probability responses.",
      },
      {
        label: "Presence Penalty",
        pref: PREFS.LLM_PRESENCE_PENALTY,
        type: "number",
        step: 0.1,
        min: -2,
        max: 2,
        tooltip:
          "Penalizes repeated tokens. Reduces repetition of information already in the context.",
      },
      {
        label: "Frequency Penalty",
        pref: PREFS.LLM_FREQUENCY_PENALTY,
        type: "number",
        step: 0.1,
        min: -2,
        max: 2,
        tooltip: "Penalizes frequent tokens. Discourages repetition of the same words/phrases.",
      },
      {
        label: "Max Output Tokens",
        pref: PREFS.LLM_MAX_OUTPUT_TOKENS,
        type: "number",
        step: 1,
        min: 1,
        max: 32000,
        tooltip: "Maximum number of tokens to generate.",
      },
    ];

    // Preset removed as per user request
    const advancedLLMResetPrefs = advancedLLMSettings.map((s) => s.pref);

    const advancedLLMSectionHtml = this._createCheckboxSectionHtml(
      "Advanced LLM Settings",
      advancedLLMSettings,
      false,
      "", // No preset selector
      "",
      advancedLLMResetPrefs
    );

    // Section 8: Browser Findbar
    const browserFindbarSettings = [
      { label: "Find as you Type", pref: "accessibility.typeaheadfind" },
      {
        label: "Enable sound (when word not found)",
        pref: "accessibility.typeaheadfind.enablesound",
      },
      { label: "Entire Word", pref: "findbar.entireword" },
      { label: "Highlight All", pref: "findbar.highlightAll" },
    ];
    const browserSettingsHtml = this._createCheckboxSectionHtml(
      "Browser Findbar",
      browserFindbarSettings,
      false,
      "",
      "",
      browserFindbarSettings.map((s) => s.pref)
    );

    // Section 9: Development
    const devSettings = [{ label: "Debug Mode (logs in console)", pref: PREFS.DEBUG_MODE }];
    const devSectionHtml = this._createCheckboxSectionHtml("Development", devSettings, false);

    return `
      <div id="ai-settings-modal-overlay">
        <div class="browse-bot-settings-modal">
          <div class="ai-settings-header">
            <h3>Settings</h3>
            <div>
              <button id="close-settings" class="settings-close-btn">Close</button>
              <button id="save-settings" class="settings-save-btn">Save</button>
            </div>
          </div>
          <div class="ai-settings-content">
            ${findbarSectionHtml}
            ${shortcutsSectionHtml}
            ${aiBehaviorSectionHtml}
            ${contextMenuSectionHtml}
            ${llmProvidersSectionHtml}
            ${advancedLLMSectionHtml}
            ${browserSettingsHtml}
            ${devSectionHtml}
          </div>
        </div>
      </div>
    `;
  },
};

/**
 * Renders markdown into a target element (marked + DOMPurify, same as urlbar-ai).
 * @param {string} markdown
 * @param {HTMLElement} target
 */
function renderMarkdown(markdown, target) {
  renderMarkdownToElement(markdown, target);
}

PREFS.setInitialPrefs();
document.documentElement.style.setProperty("--browse-bot-findbar-width", `${FINDBAR_WIDTH}px`);
document.documentElement.style.setProperty("--browse-bot-findbar-max-width", `${FINDBAR_WIDTH}px`);

const browseBotFindbar = {
  findbar: null,
  askButton: null,
  chatContainer: null,
  apiKeyContainer: null,
  _updateFindbar: null,
  _addKeymaps: null,
  _handleInputKeyPress: null,
  _handleFindFieldInput: null,
  _handleFindbarOpenEvent: null,
  _handleFindbarCloseEvent: null,
  _isExpanded: false,
  _updateContextMenuText: null,
  _backgroundStylesListener: null,
  _contextMenuEnabledListener: null,
  _persistListener: null,
  contextMenuItem: null,
  _matchesObserver: null,
  _highlightTimeout: null,
  _originalOnMatchesCountResult: null,
  _currentAIMessageDiv: null,

  /**
   * Save findbar dimensions in css variables
   */
  _updateFindbarDimensions() {
    if (!this.findbar) {
      document.documentElement.style.removeProperty("--findbar-width");
      document.documentElement.style.removeProperty("--findbar-height");
      document.documentElement.style.removeProperty("--findbar-x");
      document.documentElement.style.removeProperty("--findbar-y");
      return;
    }
    const rect = this.findbar.getBoundingClientRect();
    const _findbarDimension = { width: rect.width, height: rect.height };
    const _findbarCoors = { x: rect.left, y: rect.top };
    document.documentElement.style.setProperty("--findbar-width", `${_findbarDimension.width}px`);
    document.documentElement.style.setProperty("--findbar-height", `${_findbarDimension.height}px`);
    document.documentElement.style.setProperty("--findbar-x", `${_findbarCoors.x}px`);
    document.documentElement.style.setProperty("--findbar-y", `${_findbarCoors.y}px`);
  },

  /**
   * Apply fixed findbar width.
   */
  _applyFindbarDimensions() {
    document.documentElement.style.setProperty("--browse-bot-findbar-width", `${FINDBAR_WIDTH}px`);
    document.documentElement.style.setProperty("--browse-bot-findbar-max-width", `${FINDBAR_WIDTH}px`);

    if (!this.findbar) return;
    this.findbar.style.setProperty("width", `${FINDBAR_WIDTH}px`, "important");
    this.findbar.style.setProperty("max-width", `${FINDBAR_WIDTH}px`, "important");
    this.findbar.style.setProperty("min-width", `${FINDBAR_WIDTH}px`, "important");
  },
  _isStreaming: false,
  _abortController: null,

  get expanded() {
    return this._isExpanded;
  },
  set expanded(value) {
    const isChanged = value !== this._isExpanded;
    this._isExpanded = value;
    if (!this.findbar) return;
    this.findbar.expanded = value;
    if (isChanged) {
      setTimeout(() => this._applyFindbarDimensions(), 2);
      setTimeout(() => {
        this._applyFindbarDimensions();
        this._updateFindbarDimensions();
      }, 20);
    }

    if (value) {
      this.findbar.classList.add("ai-expanded");
      this.show();
      this.showAIInterface();
      if (isChanged) this.focusPrompt();
      const messagesContainer = this?.chatContainer?.querySelector("#chat-messages");
      if (messagesContainer) {
        messagesContainer.scrollTop = messagesContainer.scrollHeight;
      }
    } else {
      if (this._isStreaming) {
        this._abortController?.abort(); // Stop messsage if it is running
      }
      this.findbar.classList.remove("ai-expanded");
      this.removeAIInterface();
      if (isChanged) this.focusInput();
    }
  },

  get enabled() {
    return PREFS.enabled;
  },
  set enabled(value) {
    if (typeof value === "boolean") PREFS.enabled = value;
  },
  handleEnabledChange(enabled) {
    if (enabled.value) this.init();
    else this.destroy();
  },

  updateFindbar() {
    SettingsModal.hide();
    this.removeAskButton();
    this.removeAIInterface();
    if (!PREFS.persistChat) {
      this.hide();
      this.expanded = false;
      this.clear();
    }
    gBrowser.getFindBar().then((findbar) => {
      this.findbar = findbar;
      this._applyFindbarDimensions();
      this.addAskButton();
      if (PREFS.persistChat) {
        if (this?.findbar?.history) {
          browseBotFindbarLLM.history = this.findbar.history;
        } else browseBotFindbarLLM.history = [];
        if (this?.findbar?.expanded && !this?.findbar?.hidden) {
          setTimeout(() => (this.expanded = true), 200);
        } else {
          this.hide();
          this.expanded = false;
        }
      } else {
        this.hide();
        this.expanded = false;
      }
      setTimeout(() => this._updateFindbarDimensions(), 0);

      const matches = this.findbar.querySelector(".found-matches");
      const status = this.findbar.querySelector(".findbar-find-status");

      if (matches) {
        matches.hidden = true;
        matches.setAttribute("value", "");
      }
      if (status) status.hidden = true;
      this.findbar.querySelector(".findbar-find-next")?.setAttribute("disabled", "true");
      this.findbar.querySelector(".findbar-find-previous")?.setAttribute("disabled", "true");

      this.findbar._findField.removeEventListener("keypress", this._handleInputKeyPress);
      this.findbar._findField.addEventListener("keypress", this._handleInputKeyPress);
      this.findbar._findField.removeEventListener("input", this._handleFindFieldInput);
      this.findbar._findField.addEventListener("input", this._handleFindFieldInput);

      this._layoutMinimalFindbarRow();
    });
  },

  /**
   * Minimal findbar row: [textbox wrapper] [n/m matches] [Ask]
   * Native DOM: wrapper, checkboxes, .found-matches are siblings under .findbar-container.
   */
  _layoutMinimalFindbarRow() {
    if (!this.findbar) return;

    const container = this.findbar.querySelector(".findbar-container");
    const wrapper = container?.querySelector('hbox[anonid="findbar-textbox-wrapper"]');
    const matches =
      this.findbar._foundMatches || this.findbar.querySelector(".found-matches");
    const askBtn = this.askButton || container?.querySelector("#findbar-ask");

    if (!container || !wrapper || !matches) return;

    if (askBtn?.parentElement === wrapper) {
      wrapper.insertAdjacentElement("afterend", askBtn);
    }

    if (askBtn) {
      askBtn.insertAdjacentElement("beforebegin", matches);
    } else {
      wrapper.insertAdjacentElement("afterend", matches);
    }
  },

  /**
   * Highlight a word using native findbar
   * @param {string} word - Word to highlight.
   */
  highlight(word) {
    if (!this.findbar) return;

    // clear any existing timeout before starting a new one
    if (this._highlightTimeout) clearTimeout(this._highlightTimeout);

    this.findbar._find(word);

    this._highlightTimeout = setTimeout(() => {
      this.findbar.browser.finder.highlight(false);
      this._highlightTimeout = null; // cleanup
    }, 2000);
  },

  show() {
    if (!this.findbar) return false;
    this.findbar.open();
    this.focusInput();
    setTimeout(() => this._updateFindbarDimensions(), 0);
    return true;
  },
  hide() {
    if (!this.findbar) return false;
    this.findbar.close();
    this.findbar.toggleHighlight(false);
    setTimeout(() => this._updateFindbarDimensions(), 0);
    return true;
  },
  toggleVisibility() {
    if (!this.findbar) return;
    if (this.findbar.hidden) this.show();
    else this.hide();
  },

  clear() {
    browseBotFindbarLLM.clearData();
    if (this.findbar) {
      this.findbar.history = null;
    }
    const messages = this?.chatContainer?.querySelector("#chat-messages");
    if (messages) messages.innerHTML = "";
    setTimeout(() => this._updateFindbarDimensions(), 1);
  },

  createAPIKeyInterface() {
    const currentProviderName = browseBotFindbarLLM.currentProvider.name;
    const menuItems = Object.entries(browseBotFindbarLLM.AVAILABLE_PROVIDERS)
      .map(
        ([name, provider]) => `
                  <menuitem
                    value="${name}"
                    label="${escapeXmlAttribute(provider.label)}"
                    ${name === currentProviderName ? 'selected="true"' : ""}
                    ${provider.faviconUrl ? `image="${escapeXmlAttribute(provider.faviconUrl)}"` : ""}
                  />
                `
      )
      .join("");

    const menulistXul = `
        <menulist id="provider-selector" class="provider-selector" value="${currentProviderName}">
          <menupopup>
            ${menuItems}
          </menupopup>
        </menulist>`;

    const providerSelectorXulElement = parseElement(menulistXul, "xul");

    const html = `
        <div class="browse-bot-setup">
          <div class="ai-setup-content">
            <h3>AI Setup Required</h3>
            <p>To use AI features, you need to set up your API key and select a provider.</p>
            <div class="provider-selection-group">
              <label for="provider-selector">Select Provider:</label>
            </div>
            <div class="api-key-input-group">
              <input type="password" id="api-key" placeholder="Enter your API key" />
              <button id="save-api-key">Save</button>
            </div>
            <div class="api-key-links">
              <button id="get-api-key-link">Get API Key</button>
            </div>
          </div>
        </div>`;
    const container = parseElement(html);

    const providerSelectionGroup = container.querySelector(".provider-selection-group");
    // Insert the XUL menulist after the label within the group
    providerSelectionGroup.appendChild(providerSelectorXulElement);

    const providerSelector = container.querySelector("#provider-selector");
    const input = container.querySelector("#api-key");
    const saveBtn = container.querySelector("#save-api-key");
    const getApiKeyLink = container.querySelector("#get-api-key-link");
    const setupContent = container.querySelector(".ai-setup-content");
    const description = setupContent.querySelector("p");

    const updateUIForProvider = (providerName) => {
      const provider = browseBotFindbarLLM.AVAILABLE_PROVIDERS[providerName];
      if (providerName === "ollama") {
        description.textContent =
          "Ollama is selected. You can customize the Base URL below or use the default.";
        input.type = "text";
        input.placeholder = "Enter Ollama Base URL";
        input.value = PREFS.ollamaBaseUrl || "";
        getApiKeyLink.style.display = "none";
      } else {
        description.textContent =
          "To use AI features, you need to set up your API key and select a provider.";
        input.type = "password";
        input.placeholder = "Enter your API key";
        input.value = provider.apiKey || "";
        getApiKeyLink.style.display = provider.apiKeyUrl ? "inline-block" : "none";
        getApiKeyLink.disabled = !provider.apiKeyUrl;
        getApiKeyLink.title = provider.apiKeyUrl
          ? "Get API Key"
          : "No API key link available for this provider.";
      }
    };

    updateUIForProvider(currentProviderName);

    // Use 'command' event for XUL menulist
    providerSelector.addEventListener("command", (e) => {
      const selectedProviderName = e.target.value;
      browseBotFindbarLLM.setProvider(selectedProviderName); // This also updates PREFS.llmProvider internally
      updateUIForProvider(selectedProviderName);
    });

    getApiKeyLink.addEventListener("click", () => {
      openTrustedLinkIn(browseBotFindbarLLM.currentProvider.apiKeyUrl, "tab");
    });

    saveBtn.addEventListener("click", () => {
      const value = input.value.trim();
      const providerName = browseBotFindbarLLM.currentProvider.name;

      if (providerName === "ollama") {
        if (value) {
          PREFS.ollamaBaseUrl = value;
        }
        this.showAIInterface();
      } else if (value) {
        browseBotFindbarLLM.currentProvider.apiKey = value; // This also updates PREFS.mistralApiKey/geminiApiKey internally
        this.showAIInterface(); // Refresh UI after saving key
      }
    });
    input.addEventListener("keypress", (e) => {
      if (e.key === "Enter") saveBtn.click();
    });
    return container;
  },

  async sendMessage(prompt) {
    if (!prompt || this._isStreaming) return;

    this.show();
    if (!this.expanded) {
      this.expanded = true;
    } else if (!this.chatContainer) {
      this.showAIInterface();
    }

    this.addChatMessage({ role: "user", content: prompt });
    const messagesContainer = this.chatContainer?.querySelector("#chat-messages");
    if (!messagesContainer) {
      PREFS.debugError("Chat UI is unavailable.");
      return;
    }

    this._abortController = new AbortController();
    this._toggleStreamingControls(true);

    const aiMessageDiv = parseElement(
      `<div class="chat-message chat-message-ai">
        <div class="message-content">
          <div class="markdown-body"></div>
        </div>
      </div>`
    );
    const contentDiv = aiMessageDiv.querySelector(".markdown-body");
    if (messagesContainer) {
      messagesContainer.appendChild(aiMessageDiv);
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
    }
    this._currentAIMessageDiv = aiMessageDiv;

    try {
      const resultPromise = browseBotFindbarLLM.sendMessage(prompt, this._abortController.signal);

      if (!PREFS.streamEnabled) {
        const loadingIndicator = this.createLoadingIndicator();
        messagesContainer.appendChild(loadingIndicator);
        messagesContainer.scrollTop = messagesContainer.scrollHeight;

        try {
          const result = await resultPromise;
          if (loadingIndicator.parentNode) loadingIndicator.remove();

          if (result.text.trim() === "") {
            aiMessageDiv.remove();
          } else {
            renderMarkdown(result.text, contentDiv);
          }
        } finally {
          if (loadingIndicator.parentNode) loadingIndicator.remove();
          messagesContainer.scrollTop = messagesContainer.scrollHeight;
          setTimeout(() => this._updateFindbarDimensions(), 0);
        }
      } else {
        const result = await resultPromise;
        let fullText = "";
        for await (const delta of result.textStream) {
          fullText += delta;
          try {
            renderMarkdown(fullText, contentDiv);
          } catch (e) {
            PREFS.debugError("Markdown render failed:", e.message);
          }
          setTimeout(() => this._updateFindbarDimensions(), 0);
          if (messagesContainer) {
            messagesContainer.scrollTop = messagesContainer.scrollHeight;
          }
        }
        if (fullText.trim() === "") {
          aiMessageDiv.remove();
          this.addChatMessage({
            role: "error",
            content: "**Error**: The model returned an empty response. Check your API key, model, and page size.",
          });
        }
      }
    } catch (e) {
      if (e.name !== "AbortError") {
        PREFS.debugError("Error sending message:", e);
        if (aiMessageDiv) aiMessageDiv.remove();
        const errMsg = formatLlmError(e);
        this.addChatMessage({ role: "error", content: `**Error**: ${errMsg}` });
      } else {
        PREFS.debugLog("Streaming aborted by user.");
        if (aiMessageDiv) aiMessageDiv.remove();
      }
    } finally {
      this._toggleStreamingControls(false);
      this._abortController = null;
      this._currentAIMessageDiv = null;
    }
  },

  /**
   * Hide match counter and nav arrows unless there are 2+ matches.
   * @param {Element} findbarEl
   * @param {object} result
   */
  _syncFindMatchChrome(findbarEl, result) {
    if (typeof result?.current !== "number" || typeof result?.total !== "number") return;

    const hasSearch = result.searchString.trim() !== "";
    const hasMatches = hasSearch && result.total > 0;

    const next = findbarEl.querySelector(".findbar-find-next");
    const previous = findbarEl.querySelector(".findbar-find-previous");
    if (next && previous) {
      if (!hasMatches || result.total <= 1) {
        next.disabled = true;
        previous.disabled = true;
      } else if (result.current <= 1) {
        next.disabled = false;
        previous.disabled = true;
      } else if (result.current >= result.total) {
        next.disabled = true;
        previous.disabled = false;
      } else {
        next.disabled = false;
        previous.disabled = false;
      }
    }

    const status = findbarEl.querySelector(".findbar-find-status");
    if (status) {
      status.hidden = true;
    }

    const foundMatchesElement = findbarEl._foundMatches;
    if (!foundMatchesElement) return;

    if (!hasMatches) {
      foundMatchesElement.hidden = true;
      foundMatchesElement.setAttribute("value", "");
      return;
    }

    foundMatchesElement.hidden = false;
    foundMatchesElement.setAttribute("value", `${result.current}/${result.total}`);

    this._layoutMinimalFindbarRow();
  },

  _toggleStreamingControls(isStreaming) {
    this._isStreaming = isStreaming;
    if (!this.chatContainer) return;

    const sendBtn = this.chatContainer.querySelector("#send-prompt");
    const stopBtn = this.chatContainer.querySelector("#stop-generation");
    const promptInput = this.chatContainer.querySelector("#ai-prompt");
    const actions = this.chatContainer.querySelector(".ai-chat-input-actions");

    if (!sendBtn || !stopBtn) return;

    if (isStreaming) {
      sendBtn.hidden = true;
      stopBtn.hidden = false;
      actions?.setAttribute("data-streaming", "true");
      promptInput.disabled = true;
    } else {
      sendBtn.hidden = false;
      stopBtn.hidden = true;
      actions?.removeAttribute("data-streaming");
      promptInput.disabled = false;
      this.focusPrompt();
    }
  },

  // The following _overrideFindbarMatchesDisplay function is adapted from
  // aminomancer's Findbar Mods (https://github.com/aminomancer/uc.css.js/blob/master/JS/findbarMods.uc.js)
  // under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
  // Original Author: aminomancer
  // Source: https://github.com/aminomancer/uc.css.js
  // License: http://creativecommons.org/licenses/by-nc-sa/4.0/
  _overrideFindbarMatchesDisplay(retry = 0) {
    PREFS.debugLog(`_overrideFindbarMatchesDisplay called, retry: ${retry}`);
    if (this._originalOnMatchesCountResult) {
      PREFS.debugLog("Prototype already overridden.");
      return;
    }

    const findbarClass = customElements.get("findbar")?.prototype;

    if (!findbarClass) {
      PREFS.debugLog("findbarClass not found.");
      if (retry < 10) {
        setTimeout(() => this._overrideFindbarMatchesDisplay(retry + 1), 100);
        PREFS.debugLog(`Retrying _overrideFindbarMatchesDisplay in 100ms, retry: ${retry + 1}`);
      } else {
        PREFS.debugError(
          "Failed to override findbar matches display: findbar custom element not found after multiple retries."
        );
      }
      return;
    }

    PREFS.debugLog("findbarClass found. Overriding onMatchesCountResult.");
    this._originalOnMatchesCountResult = findbarClass.onMatchesCountResult;

    const self = this;
    findbarClass.onMatchesCountResult = function (result) {
      const original = self._originalOnMatchesCountResult;
      let ret;
      if (original) {
        ret = original.call(this, result);
      }

      if (PREFS.enabled) {
        self._syncFindMatchChrome(this, result);
      }

      return ret;
    };
    PREFS.debugLog("onMatchesCountResult successfully overridden.");
  },

  _restoreFindbarMatchesDisplay() {
    if (this._originalOnMatchesCountResult) {
      const findbarClass = customElements.get("findbar")?.prototype;
      if (findbarClass) {
        findbarClass.onMatchesCountResult = this._originalOnMatchesCountResult;
      }
      this._originalOnMatchesCountResult = null;

      // Reset the DOM element for the current findbar instance
      if (this.findbar) {
        const foundMatchesElement = this.findbar._foundMatches;
        if (foundMatchesElement) {
          foundMatchesElement.setAttribute("value", "");
          foundMatchesElement.hidden = true;
        }
      }
    }
  },

  createChatInterface() {
    const chatInputGroup = `<div class="ai-chat-input-group">
          <div class="ai-chat-input-shell">
            <textarea id="ai-prompt" placeholder="Ask anything about this page…" rows="1"></textarea>
            <div class="ai-chat-input-actions">
              <button id="send-prompt" class="send-btn" type="button" title="Send" aria-label="Send message">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
                  <path fill="currentColor" d="M3.4 20.4l17.45-7.48c.81-.35.81-1.49 0-1.84L3.4 3.6c-.66-.29-1.39.2-1.39.91L2 9.12c0 .5.37.93.87.99L17 12L2.87 13.88c-.5.07-.87.5-.87 1l.01 4.61c0 .71.73 1.2 1.39.91z"/>
                </svg>
              </button>
              <button id="stop-generation" class="stop-btn" type="button" title="Stop" aria-label="Stop generation" hidden>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
                  <path fill="currentColor" d="M6 6h12v12H6z"/>
                </svg>
              </button>
            </div>
          </div>
        </div>`;

    const container = parseElement(`
        <div class="browse-bot-chat">
          <div class="ai-chat-messages" id="chat-messages"></div>
          ${chatInputGroup}
        </div>`);

    const chatMessages = container.querySelector("#chat-messages");
    const promptInput = container.querySelector("#ai-prompt");
    const sendBtn = container.querySelector("#send-prompt");
    const stopBtn = container.querySelector("#stop-generation");

    const handleSend = () => {
      const prompt = promptInput.value.trim();
      this.sendMessage(prompt);
      promptInput.value = ""; // Clear input after sending
    };

    sendBtn.addEventListener("click", handleSend);
    stopBtn.addEventListener("click", () => {
      this._abortController?.abort();
    });

    promptInput.addEventListener("keypress", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    });

    chatMessages.addEventListener("keydown", (e) => {
      const excerptEl = e.target.closest(".page-excerpt");
      if (!excerptEl || e.target.closest("a")) return;
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        const quote = excerptEl.dataset.excerptQuote;
        if (quote) this.highlight(quote);
      }
    });

    chatMessages.addEventListener("click", async (e) => {
      const excerptEl = e.target.closest(".page-excerpt");
      if (excerptEl && !e.target.closest("a")) {
        const quote = excerptEl.dataset.excerptQuote;
        if (quote) {
          PREFS.debugLog("Excerpt clicked. Requesting highlight for:", quote);
          this.highlight(quote);
        }
        return;
      }

      if (e.target?.href) {
        e.preventDefault();
        try {
          openTrustedLinkIn(e.target.href, "tab");
        } catch {}
      }
    });

    return container;
  },

  createLoadingIndicator() {
    const messageDiv = parseElement(
      `<div class="chat-message chat-message-loading"><div class="message-content">Loading...</div></div>`
    );
    return messageDiv;
  },

  addChatMessage(message) {
    const { role, content } = message;
    if (!this.chatContainer || content === undefined || content === null) return;

    const messagesContainer = this.chatContainer.querySelector("#chat-messages");
    if (!messagesContainer) return;

    let type;
    switch (role) {
      case "user":
        type = "user";
        break;
      case "assistant":
        type = "ai";
        break;
      case "error":
        type = "error";
        break;
      default:
        return; // Don't display other roles like 'tool'
    }

    const messageDiv = parseElement(`<div class="chat-message chat-message-${type}"></div>`);
    const contentDiv = parseElement(`<div class="message-content markdown-body"></div>`);
    const textContent =
      typeof content === "string" ? content : (content?.answer ?? content?.[0]?.text ?? "");
    renderMarkdown(textContent, contentDiv);

    messageDiv.appendChild(contentDiv);
    messagesContainer.appendChild(messageDiv);
    messagesContainer.scrollTop = messagesContainer.scrollHeight;
    setTimeout(() => this._updateFindbarDimensions(), 10);
  },

  showAIInterface() {
    if (!this.findbar) return;
    this.removeAIInterface();

    this.findbar.classList.remove("ai-settings-active");

    if (
      !browseBotFindbarLLM.currentProvider.apiKey &&
      browseBotFindbarLLM.currentProvider.name !== "ollama"
    ) {
      this.apiKeyContainer = this.createAPIKeyInterface();
      this.findbar.insertBefore(this.apiKeyContainer, this.findbar.firstChild);
    } else {
      this.chatContainer = this.createChatInterface();
      // Re-render history using the new message format
      const history = browseBotFindbarLLM.getHistory();
      for (const message of history) {
        this.addChatMessage(message);
      }

      this.findbar.insertBefore(this.chatContainer, this.findbar.firstChild);
    }
    this._applyFindbarDimensions();
    setTimeout(() => this._updateFindbarDimensions(), 10);
  },

  focusInput() {
    if (this.findbar) setTimeout(() => this.findbar._findField.focus(), 10);
  },
  focusPrompt() {
    const promptInput = this.chatContainer?.querySelector("#ai-prompt");
    if (promptInput) setTimeout(() => promptInput.focus(), 10);
  },
  setPromptText(text) {
    const promptInput = this?.chatContainer?.querySelector("#ai-prompt");
    if (promptInput && text) promptInput.value = text;
  },
  async setPromptTextFromSelection() {
    let text = "";
    const selection = await messageManagerAPI.getSelectedText();
    if (!selection || !selection.hasSelection) text = this?.findbar?._findField?.value;
    else text = selection.selectedText;
    this.setPromptText(text);
  },

  removeAIInterface() {
    if (this.apiKeyContainer) {
      this.apiKeyContainer.remove();
      this.apiKeyContainer = null;
    }
    if (this.chatContainer) {
      this.chatContainer.remove();
      this.chatContainer = null;
    }
  },

  init() {
    if (!this.enabled) return;
    this.updateFindbar();
    this.addListeners();
    if (PREFS.contextMenuEnabled) {
      this.addContextMenuItem();
    }
    this._overrideFindbarMatchesDisplay();
  },
  destroy() {
    this.findbar = null;
    setTimeout(() => this._updateFindbarDimensions(), 10);
    this.expanded = false;
    try {
      this.removeListeners();
    } catch {}
    this.removeAskButton();
    this.removeContextMenuItem();
    this.removeAIInterface();
    SettingsModal.hide();
    this._restoreFindbarMatchesDisplay();
  },

  addAskButton() {
    if (!this.findbar) return false;

    this.removeAskButton();

    const container = this.findbar.querySelector(".findbar-container");
    if (container && !container.querySelector("#findbar-ask")) {
      const askBtn = parseElement(`<button id="findbar-ask" anonid="findbar-ask">Ask</button>`);
      askBtn.addEventListener("click", () => {
        const inpText = this.findbar._findField.value.trim();
        this.sendMessage(inpText);
        this.findbar._findField.value = "";
        this.focusInput();
      });
      const wrapper = container.querySelector('hbox[anonid="findbar-textbox-wrapper"]');
      if (wrapper) {
        wrapper.insertAdjacentElement("afterend", askBtn);
      } else {
        container.appendChild(askBtn);
      }
      this.askButton = askBtn;
      this._layoutMinimalFindbarRow();
    }
    return true;
  },

  removeAskButton() {
    if (this.askButton) {
      this.askButton.remove();
      this.askButton = null;
    }
    return true;
  },

  handleInputKeyPress: function (e) {
    if (e?.key === "Enter" && e?.altKey) {
      e.preventDefault();
      const inpText = this.findbar._findField.value.trim();
      this.sendMessage(inpText);
      this.findbar._findField.value = "";
      this.focusInput();
    }
  },

  addContextMenuItem(retryCount = 0) {
    if (this.contextMenuItem) return; // Already added
    if (!PREFS.contextMenuEnabled) return;

    const contextMenu = document.getElementById("contentAreaContextMenu");

    if (!contextMenu) {
      if (retryCount < 5) {
        PREFS.debugLog(`Context menu not found, retrying... (attempt ${retryCount + 1}/5)`);
        setTimeout(() => this.addContextMenuItem(retryCount + 1), 200);
      } else {
        PREFS.debugError(
          "Failed to add context menu item after 5 attempts: Context menu not found."
        );
      }
      return;
    }

    const menuItem = document.createXULElement("menuitem");
    menuItem.id = "browse-bot-context-menu-item";
    menuItem.setAttribute("label", "Ask AI");
    menuItem.setAttribute("accesskey", "A");

    menuItem.addEventListener("command", this.handleContextMenuClick.bind(this));
    this.contextMenuItem = menuItem;

    const searchSelectItem = contextMenu.querySelector("#context-searchselect");

    if (searchSelectItem) {
      // Insert right after the searchselect item
      if (searchSelectItem.nextSibling) {
        contextMenu.insertBefore(menuItem, searchSelectItem.nextSibling);
      } else {
        contextMenu.appendChild(menuItem);
      }
    } else {
      // Fallback: insert after context-sep-redo separator
      const redoSeparator = contextMenu.querySelector("#context-sep-redo");
      if (redoSeparator) {
        if (redoSeparator.nextSibling) {
          contextMenu.insertBefore(menuItem, redoSeparator.nextSibling);
        } else {
          contextMenu.appendChild(menuItem);
        }
      } else {
        // Final fallback: don't add the menu item if neither element is found
        return;
      }
    }

    this._updateContextMenuText = this.updateContextMenuText.bind(this);
    contextMenu.addEventListener("popupshowing", this._updateContextMenuText);
  },

  removeContextMenuItem: function () {
    this?.contextMenuItem?.remove();
    this.contextMenuItem = null;
    document
      ?.getElementById("contentAreaContextMenu")
      ?.removeEventListener("popupshowing", this._updateContextMenuText);
  },
  handleContextMenuClick: async function () {
    const selection = await messageManagerAPI.getSelectedText();
    let finalMessage = "";
    if (selection.hasSelection) {
      const commandTemplate = PREFS.contextMenuCommandWithSelection;
      finalMessage = commandTemplate.replace("{selection}", selection.selectedText);
    } else {
      finalMessage = PREFS.contextMenuCommandNoSelection;
    }
    this.expanded = true;
    if (PREFS.contextMenuAutoSend) {
      this.sendMessage(finalMessage);
      this.focusPrompt();
    } else {
      this.setPromptText(finalMessage);
      this.show();
      this.focusPrompt();
    }
  },

  handleContextMenuPrefChange: function (pref) {
    if (pref.value) this.addContextMenuItem();
    else this.removeContextMenuItem();
  },
  updateContextMenuText() {
    if (!PREFS.contextMenuEnabled || !this.contextMenuItem) return;
    const hasSelection = gContextMenu?.isTextSelected === true;
    this.contextMenuItem.label = hasSelection ? "Ask AI" : "Summarize with AI";
  },

  addKeymaps: function (e) {
    if (e.key?.toLowerCase() === "escape") {
      if (SettingsModal._modalElement && SettingsModal._modalElement.parentNode) {
        e.preventDefault();
        e.stopPropagation();
        SettingsModal.hide();
      } else if (this.expanded) {
        e.preventDefault();
        e.stopPropagation();
        this.expanded = false;
        this.focusInput();
      }
    }
  },

  addListeners() {
    this._updateFindbar = this.updateFindbar.bind(this);
    this._addKeymaps = this.addKeymaps.bind(this);
    this._handleInputKeyPress = this.handleInputKeyPress.bind(this);
    const _handleContextMenuPrefChange = this.handleContextMenuPrefChange.bind(this);
    const _handleBackgroundStyleChange = () => {
      updateSidebarWidth();
    };

    gBrowser.tabContainer.addEventListener("TabSelect", this._updateFindbar);
    document.addEventListener("keydown", this._addKeymaps);
    this._handleFindbarOpenEvent = this.handleFindbarOpenEvent.bind(this);
    this._handleFindbarCloseEvent = this.handleFindbarCloseEvent.bind(this);
    window.addEventListener("findbaropen", this._handleFindbarOpenEvent);
    window.addEventListener("findbarclose", this._handleFindbarCloseEvent);
    this._backgroundStylesListener = addPrefListener(
      PREFS.BACKGROUND_STYLE,
      _handleBackgroundStyleChange
    );
    this._contextMenuEnabledListener = addPrefListener(
      PREFS.CONTEXT_MENU_ENABLED,
      _handleContextMenuPrefChange
    );
    this._persistListener = addPrefListener(PREFS.PERSIST, (pref) => {
      if (!this.findbar) return;
      if (pref.value) this.findbar.history = browseBotFindbarLLM.history;
      else this.findbar.history = null;
    });
  },

  removeListeners() {
    if (this.findbar) {
      this.findbar._findField.removeEventListener("keypress", this._handleInputKeyPress);
      this.findbar._findField.removeEventListener("input", this._handleFindFieldInput);
    }
    gBrowser.tabContainer.removeEventListener("TabSelect", this._updateFindbar);
    document.removeEventListener("keydown", this._addKeymaps);
    window.removeEventListener("findbaropen", this._handleFindbarOpenEvent);
    window.removeEventListener("findbarclose", this._handleFindbarCloseEvent);
    removePrefListener(this._backgroundStylesListener);
    removePrefListener(this._contextMenuEnabledListener);
    removePrefListener(this._persistListener);
    this._handleInputKeyPress = null;
    this._updateFindbar = null;
    this._addKeymaps = null;
    this._contextMenuEnabledListener = null;
    this._handleFindbarOpenEvent = null;
    this._handleFindbarCloseEvent = null;
  },

  handleFindbarOpenEvent: function () {
    if (this.enabled) {
      PREFS.debugLog("Findbar is being opened");
      setTimeout(() => (this.findbar._findField.placeholder = "Press Alt + Enter to ask AI"), 100);
      setTimeout(() => this._updateFindbarDimensions(), 1);
    }
  },

  handleFindbarCloseEvent: function () {
    if (this.enabled) {
      PREFS.debugLog("Findbar is being closed");
      if (this._isStreaming) {
        this._abortController?.abort();
      }
    }
  },
};

/**
 * @param {string} domainOrUrl
 * @param {number} size
 * @returns {string}
 */
function googleFaviconAPI(domainOrUrl, size = 32) {
  let domain;
  try {
    domain = new URL(domainOrUrl).hostname;
  } catch {
    domain = domainOrUrl;
  }
  return `https://s2.googleusercontent.com/s2/favicons?domain_url=https://${domain}&sz=${size}`;
}

initMarkdownVendors();

class BrowseBotLLM {
  constructor() {
    this.history = [];
    this.AVAILABLE_PROVIDERS = createProviderFacades(PREFS);
    this.systemInstruction = "";
  }

  get streamEnabled() {
    return PREFS.streamEnabled;
  }

  get llmProvider() {
    return PREFS.llmProvider;
  }

  get currentProvider() {
    return (
      this.AVAILABLE_PROVIDERS[this.llmProvider || "gemini"] ||
      this.AVAILABLE_PROVIDERS.gemini
    );
  }

  setProvider(providerName) {
    if (this.AVAILABLE_PROVIDERS[providerName]) {
      PREFS.llmProvider = providerName;
      PREFS.debugLog(`Switched LLM provider to: ${providerName}`);
    } else {
      PREFS.debugError(`Provider "${providerName}" not found.`);
    }
  }

  getSampling() {
    return {
      temperature: PREFS.llmTemperature,
      maxTokens: PREFS.llmMaxOutputTokens,
    };
  }

  resolveActiveProvider() {
    return resolveProvider(PREFS.llmProvider || "gemini", PREFS);
  }

  getUserLocale() {
    try {
      return Services.locale.appLocaleAsBCP47 || navigator.language || "en";
    } catch {
      return navigator.language || "en";
    }
  }

  formatPageContextBlock(pageContext) {
    const url = escapeXmlAttribute(pageContext.url ?? "");
    const title = escapeXmlAttribute(pageContext.title ?? "");
    const maxContentChars = 120000;
    let content = String(pageContext.textContent ?? pageContext.content ?? "");
    if (content.length > maxContentChars) {
      content =
        content.slice(0, maxContentChars) +
        "\n\n[Page content truncated due to length. Answer using the content above.]";
    }
    const currentDate = new Date().toLocaleString(this.getUserLocale());

    return `<url>${url}</url>
<current-date>${escapeXmlAttribute(currentDate)}</current-date>
<title>${title}</title>
<content>
${content}
</content>`;
  }

  buildAskOnPagePrompt(locale, pageContextBlock) {
    return `You will be acting as a research assistant. I will give you the content of a webpage, and you will concisely answer questions from a human using information from that page. You will provide citations for all answers using <excerpt> tags.

RULES:
1. Stay in your role throughout the dialogue.
2. When asked a question, decide if you can answer based on information on the page. If the page answers the question, directly quote the relevant sentence on the page using an <excerpt> tag on its own line. Then, summarize the answer in 10 words on the next line.
3. <excerpt> tags must be on their own line, not inline.
4. If you can't provide a direct quote to support your answer, make it clear that it's just a guess.
5. Use Markdown, not HTML, to format your answer. Always **bold** the term that answers the question.
6. Be extremely concise. (1-sentence answers if possible).
7. Respond in ${locale}. Keep <excerpt> quotes in the original language of the page text when it differs from ${locale}, but write your summaries and explanations in ${locale}.
8. You may perform translations, summaries or other textual transformations for the user if asked.

EXAMPLES OF RESPONSES FOR A HYPOTHETICAL WEBPAGE:
> Why do people work in solar?
According to J.W. Peters, president of Solar Power of Oklahoma:
<excerpt>The environmental benefits are nice," he said, "but most people are doing this for the financial opportunity.</excerpt>
So, mostly **financial, not environmental, reasons**.
(Notice how the answer provides a direct quote from the page, on its own line, and the key answer is bold.)

> What's the most populous borough in NYC?
I think it's **Brooklyn**, but it's not mentioned on the page.
(Notice how it is clear that the answer comes from background knowledge, not the webpage.)

> privacy policy
According to the page:
<excerpt>[Privacy Policy](https://arc.net/privacy/#arc-max</excerpt>
(Notice how the answer is provided by the excerpt, in Markdown.)

> summary
(You would provide a brief summary)

WEBPAGE CONTEXT FOR OUR DIALOGUE:
${pageContextBlock}`;
  }

  async getSystemPrompt() {
    let systemPrompt = "";

    if (PREFS.customSystemPrompt) {
      systemPrompt = PREFS.customSystemPrompt + "\n\n";
    }

    const pageContext = await messageManagerAPI.getPageTextContent(false);
    const pageContextBlock = this.formatPageContextBlock(pageContext);
    const locale = this.getUserLocale();

    systemPrompt += this.buildAskOnPagePrompt(locale, pageContextBlock);
    return systemPrompt;
  }

  getHistory() {
    return [...this.history];
  }

  clearData() {
    PREFS.debugLog("Clearing LLM history.");
    this.history = [];
    this.systemInstruction = "";
  }

  async sendMessage(prompt, abortSignal) {
    PREFS.debugLog("Sending message via fetch-based LLM");

    const provider = this.resolveActiveProvider();
    if (provider.needsApiKey && !provider.apiKey) {
      throw new Error(`Missing API key for ${provider.label}. Add it in BrowseBot settings.`);
    }

    this.history.push({ role: "user", content: prompt });
    const systemPrompt = await this.getSystemPrompt();
    const messages = buildChatMessages(systemPrompt, this.history);
    const sampling = this.getSampling();

    if (this.streamEnabled) {
      const self = this;
      const stream = streamChatText(provider, messages, abortSignal, sampling);
      let accumulated = "";

      const textStream = (async function* () {
        for await (const chunk of stream) {
          accumulated += chunk;
          yield chunk;
        }
        self.history.push({ role: "assistant", content: accumulated });
        if (browseBotFindbar?.findbar) {
          browseBotFindbar.findbar.history = self.getHistory();
        }
      })();

      return {
        textStream,
        get text() {
          return (async () => {
            let t = "";
            for await (const c of textStream) t += c;
            return t;
          })();
        },
      };
    }

    const text = await completeChatText(provider, messages, abortSignal, sampling);
    this.history.push({ role: "assistant", content: text });
    if (browseBotFindbar?.findbar) {
      browseBotFindbar.findbar.history = this.getHistory();
    }
    return { text };
  }
}

const browseBotFindbarLLM = new BrowseBotLLM();
window.browseBotFindabrLLM = browseBotFindbarLLM;

function startupFinish(callback) {
  if (document.readyState === "complete") callback();
  else window.addEventListener("load", callback, { once: true });
}

function setupCommandPaletteIntegration(retryCount = 0) {
  if (window.ZenCommandPalette) {
    PREFS.debugLog("Integrating with Zen Command Palette...");

    window.ZenCommandPalette.addCommands([
      {
        key: "browsebot:summarize",
        label: "Summarize Page",
        command: () => {
          browseBotFindbar.expanded = true;
          browseBotFindbar.sendMessage(PREFS.contextMenuCommandNoSelection);
          browseBotFindbar.focusPrompt();
        },
        condition: () => PREFS.enabled,
        icon: "chrome://global/skin/icons/highlights.svg",
        tags: ["AI", "Summarize", "BrowseBot", "findbar"],
      },
      {
        key: "browsebot:settings",
        label: "Open BrowseBot Settings",
        command: () => SettingsModal.show(),
        icon: "chrome://global/skin/icons/settings.svg",
        tags: ["AI", "BrowseBot", "Settings"],
      },
      {
        key: "browsebot:expand-findbar",
        label: "Expand findbar AI",
        command: () => (browseBotFindbar.expanded = true),
        condition: () => PREFS.enabled,
        icon: "chrome://global/skin/icons/highlights.svg",
        tags: ["AI", "BrowseBot", "findbar"],
      },
    ]);

    PREFS.debugLog("Zen Command Palette integration successful.");
  } else {
    PREFS.debugLog("Zen Command Palette not found, retrying in 1000ms");
    if (retryCount < 10) {
      setTimeout(() => setupCommandPaletteIntegration(retryCount + 1), 1000);
    } else {
      PREFS.debugError("Could not integrate with Zen Command Palette after 10 retries.");
    }
  }
}

function registerFindbarShortcut(value = PREFS.shortcutFindbar) {
  if (!browseBotFindbar.enabled) return;
  registerShortcut(value, "toggle-findbar-ai-bar", () => {
    browseBotFindbar.expanded = !browseBotFindbar.expanded;
  });
  initShortcutRegistry();
}

function setupShortcuts() {
  registerFindbarShortcut();
  addPrefListener(PREFS.SHORTCUT_FINDBAR, (val) => registerFindbarShortcut(val.value));
}

function init() {
  browseBotFindbar.init();
  addPrefListener(PREFS.ENABLED, (val) => {
    browseBotFindbar.handleEnabledChange(val);
    registerFindbarShortcut();
  });
  window.browseBotFindbar = browseBotFindbar;

  setupShortcuts();
  setupCommandPaletteIntegration();
}

startupFinish(init);
